language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
  - CODACY_PROJECT_TOKEN=0925482d672041289fc7394e23d02255
addons:
  postgresql: "9.4"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: 
  - coveralls
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
cache: pip
