# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170924_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
