# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170925_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='reverse_grace',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
    ]
