# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170926_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='running_early',
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('running_early', 'Running Early')], default='new', max_length=6),
        ),
    ]
