# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 03:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_nag_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag_interval',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
    ]
