# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20170913_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_after',
        ),
        migrations.AlterField(
            model_name='check',
            name='nag_interval',
            field=models.DurationField(default=datetime.timedelta(0, 7200)),
        ),
    ]
