# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170927_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='reverse_grace',
        ),
    ]
