# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170913_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='last_nag',
        ),
        migrations.AddField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
