# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170913_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_mode',
            field=models.BooleanField(default=False),
        ),
    ]
